---
title: "QMM"
output:
  pdf_document: default
  html_document: default
date: "2023-09-23"
---
Question :
The Weigelt Corporation has three branch plants with excess production capacity. Fortunately, the corporation has a new product ready to begin production, and all three plants have this capability, so some of the excess capacity can be used in this way. This product can be made in three sizes–large, medium, and small–that yield a net unit profit of $420, $360, and $300, respectively. Plants 1, 2, and 3 have the excess capacity to produce 750, 900, and 450 units per day of this product, respectively, regardless of the size or combination of sizes involved.
The amount of available in-process storage space also imposes a limitation on the production rates of the new product. Plants 1, 2, and 3 have 13,000, 12,000, and 5,000 square feet, respectively, of in-process storage space available for a day’s production of this product. Each unit of the large, medium, and small sizes produced per day requires 20, 15, and 12 square feet, respectively. Sales forecasts indicate that if available, 900, 1,200, and 750 units of the large, medium, and small sizes, respectively, would be sold per day.
At each plant, some employees will need to be laid off unless most of the plant’s excess production capacity can be used to produce the new product. To avoid layoffs if possible, management has decided that the plants should use the same percentage of their excess capacity to produce the new product. Management wishes to know how much of each of the sizes should be produced by each of the plants to maximize profit.

a. Define the decision variables

The decision variables are the number of units of the new product, regardless its size, that should be produced on each plant to maximize the company’s profit.

Note:

$Xi$ = means the number of units produced on each plant, where $i$= 1 (Plant 1), 2 (Plant 2), and 3 (Plant 3).

L, M, and S = means the product's size, where L = large, M = medium, and S = small.
The decision variables are:

$iL$ = number of large items produced on plant $i$, where $i$= 1 (Plant 1), 2 (Plant 2), and 3 (Plant 3).

$iM$ = number of medium items produced on plant $i$, where $i$= 1 (Plant 1), 2 (Plant 2), and 3 (Plant 3).

$iS$ = number of small items produced on plant $i$, where $i$= 1 (Plant 1), 2 (Plant 2), and 3 (Plant 3).
b. Formulate a linear programming model for this problem.

Let

$iL$ = number of large items produced on plant $i$, where $i$= 1 (Plant 1), 2 (Plant 2), and 3 (Plant 3).

$iM$ = number of medium items produced on plant $i$, where $i$= 1 (Plant 1), 2 (Plant 2), and 3 (Plant 3).

$iS$ = number of small items produced on on plant $i$, where $i$= 1 (Plant 1), 2 (Plant 2), and 3 (Plant 3).
Maximize profit

$Z= 420 \ (L1 + L2 + L3) + 360 \ (M1 + M2 + M3) + 300 \ (S1 + S2 + S3)$
Constraints:


$L1 + M1 + S1 \le 750$

$L2 + M2 + S2 \le 900$

$L3 + M3 + S3 \le 450$

$20 L1 + 15 M1 + 12 S1 \le 13000$

 $20 L2 + 15 M2 + 12 S2 \le 12000$
 
$20 L3 + 15 M3 + 12 S3 \le 5000$

$L = L1 + L2 + L3 \ 900$

$M = M1 + M2 + M3 \ 1200$

$S = S1 + S2 + S3 \ 750$
The plants should use the same percentage of their excess capacity to produce the new product.

$\dfrac {L1 + M1 + S1} {750}$ = $\dfrac {L2 + M2 + S2} {900}$ = $\dfrac {L3 + M3 + S3} {450}$


  It can be simplified as:

      a) $900 (L1 + M1 + S1) - 750 (L2 + M2 + S2) = 0$

      b) $450 (L2 + M2 + S2) - 900 (L3 + M3 + S3) = 0$

      c) $450 (L1 + M1 + S1) - 750 (L3 + M3 + S3) = 0$
All values must be greater or equal to zero

$L, M,$ and $S \ge 0$

$iL, $iM and $iS \ge 0$

```{r}
library(lpSolve)
my_obj <- c(420, 360, 300, 420, 360, 300,420, 360, 300)

my_const <- matrix(c(1, 1, 1, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 1, 1, 1, 0 ,0, 0,
                        0, 0, 0, 0, 0, 0, 1, 1, 1,
                        20, 15, 12, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 20, 15, 12, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 20, 15, 12,
                        1, 0, 0, 1, 0, 0, 1, 0, 0,
                        0, 1, 0, 0, 1, 0, 0, 1, 0,
                        0, 0, 1, 0, 0, 1, 0, 0, 1,
                        900, 900, 900, -750, -750, -750, 0, 0, 0,
                        0, 0, 0, 450, 450, 450, -900, -900, -900,
                        -450, -450, -450, 0, 0, 0, 750, 750, 750), nrow = 12, byrow = TRUE)

my_const

my_rhs <- c(750,
                 900,
                 450,
                 13000,
                 12000,
                 5000,
                 900,
                 1200,
                 750,
                 0,
                 0,
                 0)

my_signs <- c("<=",
              "<=",
              "<=",
              "<=",
              "<=",
              "<=",
              "<=",
              "<=",
              "<=",
              "=",
              "=",
              "=")

lp("max", my_obj, my_const, my_signs, my_rhs)

lp("max", my_obj, my_const, my_signs, my_rhs)$solution

```



































































